apiVersion: v1
kind: Service
metadata:
  name: oct-streamlit-app
spec:
  selector:
    app: oct-streamlit-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 # External port
      targetPort: 8501 # Streamlit app port inside the container
