name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: asadacr9876.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t asadacr9876.azurecr.io/oct-streamlit-app:latest .
          docker push asadacr9876.azurecr.io/oct-streamlit-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "v1.30.10" # Match your cluster version

      - name: Authenticate to Azure
        run: |
          echo "${{ secrets.AZURE_CREDENTIALS }}" > azure_auth.json
          az login --service-principal --username "$(jq -r .clientId azure_auth.json)" \
                   --password "$(jq -r .clientSecret azure_auth.json)" \
                   --tenant "$(jq -r .tenantId azure_auth.json)"
          rm -f azure_auth.json

      - name: Deploy to AKS
        run: |
          kubectl apply -f deployment.yaml --validate=false
          kubectl apply -f service.yaml --validate=false
          kubectl apply -f hpa.yaml --validate=false

      - name: Verify Deployment
        run: |
          kubectl get pods
          kubectl get svc
